server.port=8761
spring.application.name=eureka-server

# Eureka server khud ko register na kare
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Dashboard enable karo
eureka.server.enable-self-preservation=false

spring.main.banner-mode=off
logging.level.com.netflix.eureka=WARN
logging.level.com.netflix.discovery=WARN